/* pixeldata.js
   The pixel artwork itself, written as grids of characters with a colour for
   each letter. Houses and cabins, the three tree types, bushes, the farm
   props (tractor and vegetable rows) and the sun and moon.
   Edit these grids to redraw anything in the scene. */

import { GLOW_CHERRY, GLOW_GREEN } from "./pixelcore.jsx";

export const HOUSE_GRIDS = {
  /* Log cabins in one shared style: stacked log courses with protruding
     corner log ends, dark shingled roof with an overhanging eave, chimney
     with drifting smoke, warm windows, and a soft grounded shadow.
     A = login card, B = the detailed front cabin, C = the smaller, plainer
     cabin across the stream. */
  A: {
    rows: [
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      ".....................",
      "................S.S..",
      ".................S...",
      "................S....",
      "...............cc....",
      "...............CC....",
      "........KEEEk..CC....",
      "......KKKkKKKKKCC....",
      "....KKkKKKKKkKKCC....",
      "..KkKKKKKkKKKKKCCKK..",
      "EEEEEEEEEEEEEEEEEEEEE",
      "..OOlllllllllllllOO..",
      "..ooLVVVLLLLLLLLLoo..",
      "..OOlVXVlddddllllOO..",
      "..ooLVVVLdDDdLLLLoo..",
      "..OOllllldDDdllllOO..",
      "..ooLLLLLdDDdLLLLoo..",
      "..FFFFFFFFFFFFFFFFF..",
      ".HHHHHHHHHHHHHHHHHHH.",
    ],
    palette: { C: "#463034", D: "#2e2126", E: "#34222a", F: "#7a5a3a", H: "rgba(58,42,30,0.20)", K: "#4a3033", L: "#b5763f", O: "#d99a5c", c: "#6b4a3c", d: "#4a3229", k: "#5c3c40", l: "#c98a52", o: "#a56a37", V: "#6b4a30"},
  },
  B: {
    /* Main near-side cabin: log walls with corner and centre log-end posts
       running to the ground, dark shingled roof sitting flush on the wall
       top, central front gable, chimney and smoke, three warm windows. */
    rows: [
      ".........................................",
      ".........................................",
      ".........................................",
      ".........................................",
      ".........................................",
      ".........................................",
      ".........................................",
      "..............................S.S.S......",
      ".............................S.S.S.......",
      "..............................S.S.S......",
      ".............................S.S.S.......",
      "..............................ccc........",
      "..............................CCC........",
      "..............................CCC........",
      "..............................CCC........",
      ".............EEEEEEEEEEEEEEE..CCC........",
      "...........kKKKKKKkKKKKKKkKKKKCCC........",
      ".........KKKKKKkKKKKKKkKKKKKKkCCC........",
      ".......KKKKKkKKKKKKEkEKKKKkKKKCCCk.......",
      ".....KKKKkKKKKKKkKEkkkEkKKKKKKkKKKKK.....",
      "...KKKkKKKKKKkKKKEkkkkkEKKKkKKKKKKkKKK...",
      ".KKkKKKKKKkKKKKKEkkkkkkkEKKKKKKkKKKKKKkK.",
      "EEEEEEEEEEEEEEEEkkkkkkkkkEEEEEEEEEEEEEEEE",
      "..OolllllllOollllllllllllllOollllllllOo..",
      "..OoLLLLLLLOoLLLLLLLLLLLLLLOoLLLLLLLLOo..",
      "..OolllllllOollllllllllllllOollllllllOo..",
      "..OogVVVVVgOogVVVVVgdDDdgggOogVVVVVggOo..",
      "..OolVXVXVlOolVXVXVldDDdlllOolVXVXVllOo..",
      "..OoLVVVVVLOoLVVVVVLdDDdLLLOoLVVVVVLLOo..",
      "..OogVXVXVgOogVXVXVgdDDdgggOogVXVXVggOo..",
      "..OoLVVVVVLOoLVVVVVLdDDdLLLOoLVVVVVLLOo..",
      "..OolllllllOollllllldDDdlllOollllllllOo..",
      "..OogggggggOogggggggdDDdgggOoggggggggOo..",
      "..OolllllllOollllllldDDdlllOollllllllOo..",
      "..OoLLLLLLLOoLLLLLLLdDDdLLLOoLLLLLLLLOo..",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
    ],
    palette: { K: "#8b5a3c", k: "#7a4c31", E: "#6e4327", l: "#c79a63", L: "#a87d4d", g: "#8a5f3a", O: "#cfa26a", o: "#8f6740", d: "#7a5a3a", D: "#6e5236", C: "#7a5a3a", c: "#a8764e", F: "#a97c4f", H: "rgba(58,42,30,0.20)" , n: "#a8764e", V: "#6b4a30"},
  },
  C: {
    rows: [
      "...............",
      "...............",
      "...............",
      "...............",
      "...............",
      "...............",
      "...............",
      "...............",
      "...............",
      "..........S....",
      "...........S...",
      "..........cc...",
      "..........CC...",
      "......kKK.CC...",
      "....kKKKKKCC...",
      "..kKKKKKkKKKK..",
      "EEEEEEEEEEEEEEE",
      "..lllllllllll..",
      "..LLLLLLLVVVL..",
      "..llldDdlVXVl..",
      "..LLLdDdLVVVL..",
      "..llldDdlllll..",
      "..FFFFFFFFFFF..",
      ".HHHHHHHHHHHHH.",
    ],
    palette: { C: "#463034", D: "#2e2126", E: "#34222a", F: "#7a5a3a", H: "rgba(58,42,30,0.20)", K: "#4a3033", L: "#b5763f", c: "#6b4a3c", d: "#4a3229", k: "#5c3c40", l: "#c98a52", V: "#6b4a30"},
  },
};

export const TREE_GRIDS = {
  /* Clustered light-to-shadow foliage over a solid trunk. No dark cells
     are painted into the canopy, which previously read as stray lines. */
  cherry: {
    rows: [
      "............B............",
      "........AhAAhBBAA........",
      "......AAABaBBaBAAAB......",
      "....AAAABCBBBABAAAAAA....",
      "...AAABABChBBBBABBAAAA...",
      "..AAAABBCBAaAABABBBCDCB..",
      "..AAhABhCBAAAAhBBCBChCC..",
      ".ABAAaBBaAAABBBaCCDDCaBB.",
      ".AAAAAAAAAAACCBBCCDDCDDC.",
      "..AAhBAAAAhBCCBBChDDDDC..",
      "..AAAaAAAABaCCCBBCaDDDD..",
      ".BBBCCBBBBBBCCDCCCDDDDDD.",
      "..BBCCBCBBBBDCDCCCDDDDD..",
      "..CCABBBBBBBDDDCCBDDDDD..",
      "....BCCBBBBCCCCDCCDDD....",
      ".......BBBCCBBDDDD.......",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "...........tTT...........",
      "..........rrrrr..........",
    ],
    palette: { A: "#fbe0ea", B: "#f6c2d6", C: "#e79bbb", D: "#cd7ba1", T: "#7a5540", r: "#5d3f2f", t: "#956a4d", a: "#c2436f", h: "#ffd9e8"},
    glow: GLOW_CHERRY,
  },
  green: {
    rows: [
      "...........A...........",
      ".......AAAAAAABA.......",
      ".....AAAAAAAAAhBCB.....",
      "....AhAAAhAABAAaAAC....",
      "...AAAaAAAaABBABBBCC...",
      "..AAAAAABBBBhCCBAACCD..",
      ".AAAhAAhABBBCaCBAACCDD.",
      ".BBAAaAAaCBBCCDBAhDDCC.",
      ".AAAAAAABCBBCCCCBBaDDB.",
      ".ABAAAAAABBCCCCCBCDCDC.",
      ".ABhAABBBBhCCCCCBCDDDC.",
      "..BBaACCDCCaCCBDCCBCC..",
      "...BAACCDBCCCDhDCCCC...",
      "....AADCDBhCBBBaDDC....",
      "....CCBBBDDaDDDCDDD....",
      "......ABBCDDDDDDD......",
      "........BCDDDDD........",
      "..........tTT..........",
      "..........tTT..........",
      "..........tTT..........",
      "..........tTT..........",
      "..........tTT..........",
      "..........tTT..........",
      ".........rrrrr.........",
    ],
    palette: { A: "#a9d582", B: "#7fb85e", C: "#5c9445", D: "#416d2f", T: "#6b4a30", r: "#4f3623", t: "#8a6240", a: "#2f6b31", h: "#bfe6a0"},
    glow: GLOW_GREEN,
  },
  conifer: {
    rows: [
      "........ABB........",
      "........AAB........",
      ".......AAAAA.......",
      "......BBAhBAB......",
      "......BBAAaAC......",
      ".....AAABABBBA.....",
      ".....ABhBBBBBA.....",
      "......BCaBAAA......",
      ".....CBBBCBBBB.....",
      "....hCABBBBBCCC....",
      "....CaAAeCBBhDD....",
      "...BBCBBCCCDDaDD...",
      "....CCBBChCDDCD....",
      "...ChCCCDDaDCBCC...",
      "..BCBaCCCDDDBBBDD..",
      ".CBBBCCCCeDDCCCDDD.",
      "....CCCCDDDDCCD....",
      "...CDDCCDDhDDDDD...",
      "..BCeDCCDDDaDDDDD..",
      ".CBCDDDDDCCCDDDDDD.",
      "........tTT........",
      "........tTT........",
      "........tTT........",
      "........tTT........",
      ".......rrrrr.......",
    ],
    palette: { A: "#7fb85e", B: "#5c9445", C: "#416d2f", D: "#2f5222", T: "#6b4a30", r: "#4f3623", t: "#8a6240", a: "#27552a", h: "#a9d582", e: "#2f5d2a"},
    glow: GLOW_GREEN,
  },
};

export const BUSH_GRIDS = {
  /* Low flowering mounds; the floral variant mixes white, yellow, pink
     and red blooms the way the reference flower-bush row does. */
  floral: {
    rows: [
      "...........FYAAB...........",
      ".....q...AAAPAABAA...A.....",
      "..BAAAAyBAAqAAAWCCBBBBAAB..",
      ".CCCBwAFABBBCCBBCCCBDBABCB.",
      "BYBBpBBBBBPCBpBBDDCCqACCCCB",
      "BBCBWCBBBBCCwCCCDDCDFYCCDDP",
      "wBAWDCDDCCCByCFCDCDYCCDDDDD",
      ".CyCDCPDpCCCCDDDDDDDDCDDDC.",
      "..AWDDCCDCCDDFCDDDDYDPDDD..",
    ],
    palette: { A: "#a9d582", B: "#7fb85e", C: "#5c9445", D: "#416d2f", p: "#f5a8c4", q: "#e2607f", w: "#fdf6e3", y: "#f7d566", F: "#f3a5b5", Y: "#f7d566", P: "#c9a4e4", W: "#fdf6e3"},
  },
  green: {
    rows: [
      "...........YPABA...........",
      ".....A...BBBWBBAAA...B.....",
      "..AABBAAAABBBBBYABBBCBAAA..",
      ".AAABBAPBCCCBBBBAABCCCBBBB.",
      "BWAAAABBABYDABBABBDDCCDCBBC",
      "BBBAPBCBBCDDWBCBCBDDYPCDBBW",
      "CCBYDDBBACDDCCPDDDBWCDDDDDD",
      ".CCCDDYABCDDCCDDDDCCCDDDDD.",
      "..CPDDCCCDDDCWDDCCDYBPDDD..",
    ],
    palette: { A: "#a9d582", B: "#7fb85e", C: "#5c9445", D: "#416d2f", Y: "#f7d566", P: "#c9a4e4", W: "#fdf6e3"},
  },
};

/* Warm twinkling highlights scattered over foliage at night. Positions are
   fixed per index so they don't jump between renders. */

export const FARM_PROPS = {
  hay: {
    /* Stacked bales beside the cabin's right wall. */
    rows: [
      "....yyyyyy......",
      "....yYYYYy......",
      "....yyyyyy......",
      "....yYYYYy......",
      "....dddddd......",
      ".yyyyyy.yyyyyy..",
      ".yYYYYy.yYYYYy..",
      ".yyyyyy.yyyyyy..",
      ".yYYYYy.yYYYYy..",
      ".dddddd.dddddd..",
      ".yyyyyy.yyyyyy..",
      ".yYYYYy.yYYYYy..",
      ".yyyyyy.yyyyyy..",
      ".yYYYYy.yYYYYy..",
      ".dddddd.dddddd..",
      "HHHHHHHHHHHHHHHH",
    ],
    palette: { y: "#e0b95c", Y: "#f0d489", d: "#b8913f", H: "rgba(58,42,30,0.20)" },
  },
  veg: {
    /* Rows running back from the cabin wall: 5, then 4, then 3 plants,
       each row's soil only as wide as its own crops. */
    rows: [
      "..................kkkk..kkkk..kkkk",
      "..................kKKk..kKKk..kKKk",
      "..................kkkk..kkkk..kkkk",
      "..................GGGGGGGGGGGGGGGG",
      "..........l......l......l......l..",
      "........llllq..llllq..llllq..llllq",
      "........lllll..lllll..lllll..lllll",
      "........qlQll..qlQll..qlQll..qlQll",
      "........GGGGGGGGGGGGGGGGGGGGGGGGGG",
      ".....lllll.lllll.lllll.lllll.lllll",
      ".....lllll.lllll.lllll.lllll.lllll",
      ".....lllll.lllll.lllll.lllll.lllll",
      ".....ooooo.ooooo.ooooo.ooooo.ooooo",
      ".....GGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
      ".....HHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
    ],
    palette: { k: "#5f8f45", K: "#7fb85e", l: "#6f9e4f", q: "#d1434a", Q: "#e8656b", o: "#e08a3c", G: "#7a5a3a", H: "rgba(58,42,30,0.20)" },
  },
  tractor: {
    rows: [
      "....................",
      "....e...............",
      "....eRRRRRRR........",
      "....eRWWWWWR........",
      "....eRWWWWWR........",
      "...RRRRRRRRRRRRR....",
      "...RRRRRRRRRrrrr....",
      "..rrRRRRRRRRrrrr....",
      "..rTTTT.............",
      "...ThhT.....ThT.....",
      "...TTTT.....TTT.....",
      "HHHHHHHHHHHHHHHHHHHH",
    ],
    palette: { H: "rgba(58,42,30,0.20)", R: "#c0413f", T: "#33302f", W: "#cfe4ef", e: "#5b5b5b", h: "#6e6a68", r: "#9c3230" },
  },
};

/* ===================== Night sky pieces ===================== */

export const SUN_GRID = {
  rows: [
    "..........C..........",
    "..........C..........",
    "...C.....CBC.....C...",
    "....CC.........CC....",
    "....CB..DDDDD..BC....",
    ".......DAAAABD.......",
    "......DAAAABBBD......",
    ".....DAAAABBBBBD.....",
    "...C.DAAABBBBBBD.C...",
    ".CCB.DAABBBBBBBD.BCC.",
    "...C.DABBBBBBBBD.C...",
    ".....DBBBBBBBBBD.....",
    "......DBBBBBBBD......",
    ".......DBBBBBD.......",
    "....CB..DDDDD..BC....",
    "....CC.........CC....",
    "...C.....CBC.....C...",
    "..........C..........",
    "..........C..........",
  ],
  palette: { A: "#ffe9a8", B: "#ffd968", C: "#f5c542", D: "#e8a93b" },
};

export const MOON_GRID = {
  rows: [
    "......AAAAAAA......",
    ".....AAAAAAAAA.....",
    "...AAAAAAAAAAAAA...",
    "...AAACAAACAAABA...",
    "..AAACCCACCCAABBB..",
    ".AAACCCCCACABAAABB.",
    ".AAAACCCAAAABCBBBB.",
    ".AAAAACABAAACCCCBC.",
    ".AAAAAAAAABCCDBBCC.",
    ".AABAABBBBCCCCCCCC.",
    ".AABCCCBBBCDDDDCCD.",
    ".BABCCCBBCDDDDDCDC.",
    "..BBCCDCBCCDDDDDC..",
    "...BBBBCCCCCCCDC...",
    "...CBCBCCCCCDDDD...",
    ".....CCDCCDCDD.....",
    "......CCCCCDD......",
  ],
  palette: { A: "#f2f5fb", B: "#d3dae7", C: "#aeb8c8", D: "#8d99ad" },
};
